//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva2WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        public int Project_ID { get; set; }
        public int User_ID { get; set; }
        public int Category_ID { get; set; }
        public Nullable<int> Subcategory_ID { get; set; }
        public string Title { get; set; }
        public int Country_ID { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public string Video { get; set; }
        public Nullable<int> FundingDuration { get; set; }
        public Nullable<decimal> FundingGoal { get; set; }
        public Nullable<int> Currency_ID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Funded { get; set; }
    }
}
