//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva2WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategories
    {
        public int SubCategory_ID { get; set; }
        public string Description { get; set; }
        public int Category_ID { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
