//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viva2WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int User_ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Trusted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> ActivatedAccount { get; set; }
        public Nullable<bool> DeletedAccount { get; set; }
        public string Username { get; set; }
    }
}
