//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIva2DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Backers
    {
        public int Backer_ID { get; set; }
        public int User_ID { get; set; }
        public int Project_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public /*virtual*/ Projects Projects { get; set; }
        public /*virtual*/ Users Users { get; set; }
    }
}
