//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIva2DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int Image_ID { get; set; }
        public int Project_ID { get; set; }
        public string ContentType { get; set; }
        public byte[] Data { get; set; }

        public /*virtual*/ Projects Projects { get; set; }
    }
}
