//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIva2DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects()
        {
            this.Backers = new HashSet<Backers>();
            this.Rewards = new HashSet<Rewards>();
            this.Images = new HashSet<Images>();
        }
    
        public int Project_ID { get; set; }
        public int User_ID { get; set; }
        public int Category_ID { get; set; }
        public Nullable<int> Subcategory_ID { get; set; }
        public string Title { get; set; }
        public int Country_ID { get; set; }
        public string Description { get; set; }
        public string Video { get; set; }
        public Nullable<int> FundingDuration { get; set; }
        public Nullable<decimal> FundingGoal { get; set; }
        public Nullable<int> Currency_ID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Funded { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> DateActivated { get; set; }

        public /*virtual*/ Categories Categories { get; set; }
        public /*virtual*/ Countries Countries { get; set; }
        public /*virtual*/ Currencies Currencies { get; set; }
        public /*virtual*/ SubCategories SubCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public /*virtual*/ ICollection<Backers> Backers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public /*virtual*/ ICollection<Rewards> Rewards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public /*virtual*/ ICollection<Images> Images { get; set; }
    }
}
