//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIva2DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvw_ProjectDetails
    {
        public int Project_ID { get; set; }
        public Nullable<int> RemainingTime { get; set; }
        public string PercentageFunded { get; set; }
        public Nullable<int> Backers { get; set; }
        public decimal AmmountFunded { get; set; }
    }
}
